<?php
// Enable error reporting for debugging
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

session_start(); // Start the session at the beginning of the script

// Include Composer's autoload file
require_once 'vendor/autoload.php'; // Autoload Composer dependencies
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Visitor IP Logger with Time Calculation</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <style>
        body {
            background-color: #f7fafc;
        }
    </style>
</head>

<body class="font-sans">

    <header class="bg-blue-600 text-white p-6">
        <h1 class="text-3xl font-bold text-center">Cybersecurity Awareness</h1>
        <p class="text-center mt-2">Stay Safe Online and Protect Your Data</p>
    </header>
    <section class="max-w-6xl mx-auto p-6">

        <section class="my-8">
            <h2 class="text-2xl font-semibold">Common Cyber Threats</h2>
            <div class="grid grid-cols-1 md:grid-cols-2 gap-6 mt-4">
                <div class="bg-white p-4 shadow-md rounded-lg">
                    <img src="https://plus.unsplash.com/premium_photo-1661764393655-1dbffee8c0ce?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8Y3liZXIlMjBzZWN1cml0eXxlbnwwfHwwfHx8MA%3D%3D" alt="Phishing" class="w-full h-40 object-cover rounded-md">
                    <h3 class="mt-2 font-bold">1. Phishing</h3>
                    <p>Phishing attacks use fraudulent emails or messages to trick users into revealing personal information.</p>
                </div>
                <div class="bg-white p-4 shadow-md rounded-lg">
                    <img src="https://plus.unsplash.com/premium_photo-1661320941506-9fbe0aab091c?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDEzfHx8ZW58MHx8fHx8" alt="Malware" class="w-full h-40 object-cover rounded-md">
                    <h3 class="mt-2 font-bold">2. Malware</h3>
                    <p>Malware is malicious software designed to harm or exploit any programmable device or network.</p>
                </div>
                <div class="bg-white p-4 shadow-md rounded-lg">
                    <img src="https://plus.unsplash.com/premium_photo-1664299072583-584882c00a5f?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDI3fHx8ZW58MHx8fHx8" alt="Ransomware" class="w-full h-40 object-cover rounded-md">
                    <h3 class="mt-2 font-bold">3. Ransomware</h3>
                    <p>Ransomware is a type of malware that locks your files and demands payment for access.</p>
                </div>
                <div class="bg-white p-4 shadow-md rounded-lg">
                    <img src="https://plus.unsplash.com/premium_photo-1663100739979-624cb7e057c3?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDQyfHx8ZW58MHx8fHx8" alt="DDoS Attack" class="w-full h-40 object-cover rounded-md">
                    <h3 class="mt-2 font-bold">4. DDoS Attack</h3>
                    <p>A Distributed Denial of Service (DDoS) attack aims to overwhelm a service to make it unavailable.</p>
                </div>
            </div>
        </section>
        
        <section class="my-8">
            <h2 class="text-2xl font-semibold">Stay Vigilant</h2>
            <p class="mt-2">
                Cybersecurity is everyone's responsibility. By following best practices and being aware of potential threats,
                you can help protect yourself and your information from cyber attacks.
            </p>
        </section>
    </section>
    <footer class="bg-blue-600 text-white p-6">
        <p class="text-center">© 2024 DDoS Team. All Rights Reserved.</p>
    </footer>

    <?php
    // Include the script to store IP, start time, region, etc.
    include 'store_ip.php';
    ?>


    <script>
document.addEventListener("DOMContentLoaded", () => {
    // Generate or fetch the session ID from the server
    const sessionId = "<?= session_id(); ?>"; // This should be generated by PHP
    const startTime = Date.now();

    // Function to send end time and total time spent to the server
    const sendEndTime = () => {
        const endTime = Date.now();
        const totalTimeSpent = Math.round((endTime - startTime) / 1000); // Time in seconds

        // Use sendBeacon for a reliable data transfer even when the user leaves the page
        navigator.sendBeacon(
            "store_end_time.php",
            new URLSearchParams({
                session_id: sessionId,
                total_time_spent: totalTimeSpent,
            })
        );
    };

    // Add event listeners to capture when the user leaves the page
    window.addEventListener("beforeunload", sendEndTime);
    document.addEventListener("visibilitychange", () => {
        if (document.visibilityState === "hidden") {
            sendEndTime();
        }
    });
});
</script>


</body>

</html>
